name: Pylint and Pytest

on:
  push:
    branches: 
      master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install lint and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest

    - name: Install dependencies
      run: |
        pip install -r requirements/requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9 $(find . -name "*.py" | xargs)

    - name: Testing the code with pytest
      run: |
        pytest
